"""
Shared utilities for Network Topology plugin.

This package provides shared types, constants, and utility functions
used across different components of the Network Topology plugin.
"""

from .types import (
    FirewallConfig,
    Host,
    HostType,
    Infrastructure,
    Network,
    OpenCodeAgent,
    Router,
    RouterConfig,
    Topology,
    TopologySummary,
    VisualLayout,
    DataGenerationRequest,
    DataGenerationResponse,
    JobStatus,
)

from .constants import (
    BASE_IMAGE,
    OPENCODE_IMAGE,
    HOST_TYPES,
    MAX_NETWORKS,
    MAX_HOSTS_PER_NETWORK,
    DEFAULT_NETWORK_PREFIX,
    TRANSIT_NETWORK_CIDR_BITS,
)

from .utils import (
    normalize_identifier,
    slugify,
    shell_quote,
    now_ts,
    subnet_prefix,
    validate_cidr,
    router_ip,
    host_ip,
    hackerlab_ip,
    network_router_ips,
    transit_network_key,
    transit_subnet,
    cidr_contains_ip,
    is_valid_ip,
    validate_host_type,
    validate_network_count,
    validate_host_count,
    validate_ssh_credentials,
    validate_firewall_rule,
    normalize_agent_list,
    merge_agent_config,
    read_json,
    write_json,
    ensure_directory,
    build_router_maps,
    router_descendant_networks,
    get_network_by_id,
    get_router_by_id,
    count_hosts_in_topology,
    get_all_hosts,
    find_host_by_id,
    build_allowed_pairs,
    get_firewall_action,
    ssh_setup_block,
    get_router_credentials,
    get_host_credentials,
    default_host_data,
    build_topology_labels,
    generate_service_name,
    generate_router_service_name,
)

__all__ = [
    # Types
    "FirewallConfig",
    "Host",
    "HostType",
    "Infrastructure",
    "Network",
    "OpenCodeAgent",
    "Router",
    "RouterConfig",
    "Topology",
    "TopologySummary",
    "VisualLayout",
    "DataGenerationRequest",
    "DataGenerationResponse",
    "JobStatus",
    # Constants
    "BASE_IMAGE",
    "OPENCODE_IMAGE",
    "HOST_TYPES",
    "MAX_NETWORKS",
    "MAX_HOSTS_PER_NETWORK",
    "DEFAULT_NETWORK_PREFIX",
    "TRANSIT_NETWORK_CIDR_BITS",
    # Utilities
    "normalize_identifier",
    "slugify",
    "shell_quote",
    "now_ts",
    "subnet_prefix",
    "validate_cidr",
    "router_ip",
    "host_ip",
    "hackerlab_ip",
    "network_router_ips",
    "transit_network_key",
    "transit_subnet",
    "cidr_contains_ip",
    "is_valid_ip",
    "validate_host_type",
    "validate_network_count",
    "validate_host_count",
    "validate_ssh_credentials",
    "validate_firewall_rule",
    "normalize_agent_list",
    "merge_agent_config",
    "read_json",
    "write_json",
    "ensure_directory",
    "build_router_maps",
    "router_descendant_networks",
    "get_network_by_id",
    "get_router_by_id",
    "count_hosts_in_topology",
    "get_all_hosts",
    "find_host_by_id",
    "build_allowed_pairs",
    "get_firewall_action",
    "ssh_setup_block",
    "get_router_credentials",
    "get_host_credentials",
    "default_host_data",
    "build_topology_labels",
    "generate_service_name",
    "generate_router_service_name",
]
